all:
  hosts:
    node1:
      ansible_host: 3.80.89.242
      ip: 3.80.89.242
      access_ip: 3.80.89.242
    node2:
      ansible_host: 54.90.176.217
      ip: 54.90.176.217
      access_ip: 54.90.176.217
    node3:
      ansible_host: 54.89.149.54
      ip: 54.89.149.54
      access_ip: 54.89.149.54
    
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
