apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: diplom-app
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: diplom-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: diplom-app
    spec:
      containers:
        - name: diplom-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
          - containerPort: 80
            name: http